export enum ServiceStatus {
  PROCESSING = 'PROCESSING', // PENDIENTE / EN PROCESAMIENTO
  ACCEPTED = 'ACCEPTED',     // ACEPTADO
  ARRIVING = 'ARRIVING',     // ARRIVAMIENTO
  IN_PROGRESS = 'IN_PROGRESS', // EN PROGRESO
  COMPLETED = 'COMPLETED',   // FIN DEL SERVICIO

  AGENCY_CANCELED = 'AGENCY_CANCELED', // CANCELADO POR LA AGENCIA
  PROVIDER_CANCELED = 'PROVIDER_CANCELED', // CANCELADO POR EL TRANSPORTISTA
  TOURISM_CANCELED = 'TOURISM_CANCELED',   // CANCELADO POR EL TURISMO

  NO_PROVIDER_AVAILABLE = 'NO_PROVIDER_AVAILABLE', // NO HAY PROVEEDORES DISPONIBLES
}
