export enum ServiceStatus {
  PROCESSING = 'PROCESSING',
  ACCEPTED = 'ACCEPTED',
  ARRIVING = 'ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',

  AGENCY_CANCELLED = 'AGENCY_CANCELLED',
  PROVIDER_CANCELLED = 'PROVIDER_CANCELLED',

  NO_PROVIDER_AVAILABLE = 'NO_PROVIDER_AVAILABLE',
}
