export enum ServiceStatus {
  PROCESSING = 'PROCESSING',
  ACCEPTED = 'ACCEPTED',
  ARRIVING = 'ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',

  AGENCY_CANCELED = 'AGENCY_CANCELED',
  PROVIDER_CANCELED = 'PROVIDER_CANCELED',

  NO_PROVIDER_AVAILABLE = 'NO_PROVIDER_AVAILABLE',
}
