import { Component, input, output, signal, inject, ChangeDetectionStrategy } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { VehicleDetails, VehicleTypeDetailed as VehicleType, VehicleStatus } from '../../Types';
import { VehiclesAndDriversService } from '../../Services/VehiclesAndDrivers/vehicles-and-drivers.service';

export interface VehicleFormData {
    licensePlate: string;
    brand: string;
    model: string;
    year: number;
    type: VehicleType;
    capacity: number;
    color: string;
    features: string[];
    fuelType: 'gasoline' | 'diesel' | 'electric' | 'hybrid';
    mileage: number;
    photo?: string;
}

@Component({
    selector: 'cp-add-vehicle-modal',
    templateUrl: './add-vehicle-modal.component.html',
    styleUrl: './add-vehicle-modal.component.css',
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [ReactiveFormsModule]
})
export class AddVehicleModalComponent {
    // Injected services
    private fb = inject(FormBuilder);
    private vehiclesService = inject(VehiclesAndDriversService);

    // Inputs
    isOpen = input<boolean>(false);

    // Outputs
    close = output<void>();
    vehicleCreated = output<VehicleDetails>();

    // Signals
    isSubmitting = signal<boolean>(false);
    availableFeatures = signal<string[]>([
        'Aire acondicionado',
        'WiFi',
        'USB',
        'Música',
        'GPS',
        'Asientos reclinables',
        'Televisión',
        'Refrigerador',
        'Baño',
        'Cinturones de seguridad'
    ]);

    // Form
    vehicleForm: FormGroup;

    // Form data options
    vehicleTypes: { value: VehicleType; label: string }[] = [
        { value: 'carro', label: 'Automóvil' },
        { value: 'van', label: 'Van/Minivan' },
        { value: 'bus', label: 'Bus/Ómnibus' }
    ];

    fuelTypes: { value: string; label: string }[] = [
        { value: 'gasoline', label: 'Gasolina' },
        { value: 'diesel', label: 'Diésel' },
        { value: 'electric', label: 'Eléctrico' },
        { value: 'hybrid', label: 'Híbrido' }
    ];

    selectedFeatures = signal<string[]>([]);

    constructor() {
        this.vehicleForm = this.fb.group({
            licensePlate: ['', [Validators.required, Validators.pattern(/^[A-Z0-9]{3}-[A-Z0-9]{3}$/)]],
            brand: ['', [Validators.required, Validators.minLength(2)]],
            model: ['', [Validators.required, Validators.minLength(2)]],
            year: [new Date().getFullYear(), [Validators.required, Validators.min(1990), Validators.max(new Date().getFullYear() + 1)]],
            type: ['carro', Validators.required],
            capacity: [4, [Validators.required, Validators.min(1), Validators.max(50)]],
            color: ['', [Validators.required, Validators.minLength(3)]],
            fuelType: ['gasoline', Validators.required],
            mileage: [0, [Validators.required, Validators.min(0)]],
            photo: ['']
        });
    }

    onClose(): void {
        this.close.emit();
        this.resetForm();
    }

    toggleFeature(feature: string): void {
        const currentFeatures = this.selectedFeatures();
        const index = currentFeatures.indexOf(feature);

        if (index > -1) {
            // Remove feature
            this.selectedFeatures.set(currentFeatures.filter(f => f !== feature));
        } else {
            // Add feature
            this.selectedFeatures.set([...currentFeatures, feature]);
        }
    }

    isFeatureSelected(feature: string): boolean {
        return this.selectedFeatures().includes(feature);
    }

    onSubmit(): void {
        if (this.vehicleForm.valid && !this.isSubmitting()) {
            this.isSubmitting.set(true);

            const formData = this.vehicleForm.value;
            const vehicleData: VehicleFormData = {
                ...formData,
                features: this.selectedFeatures()
            };

            // Create new vehicle object
            const newVehicle: VehicleDetails = {
                id: `vehicle-${Date.now()}`, // In real app, this would be generated by the backend
                ...vehicleData,
                status: 'available' as VehicleStatus,
                lastMaintenance: new Date(),
                documents: {
                    soat: 'pending',
                    technicalReview: 'pending',
                    circulation: 'pending'
                },
                maintenanceHistory: [],
                tripHistory: []
            };

            // Simulate API call
            setTimeout(() => {
                this.vehicleCreated.emit(newVehicle);
                this.isSubmitting.set(false);
                this.onClose();
            }, 1500);
        } else {
            // Mark all fields as touched to show validation errors
            this.vehicleForm.markAllAsTouched();
        }
    }

    private resetForm(): void {
        this.vehicleForm.reset({
            licensePlate: '',
            brand: '',
            model: '',
            year: new Date().getFullYear(),
            type: 'carro',
            capacity: 4,
            color: '',
            fuelType: 'gasoline',
            mileage: 0,
            photo: ''
        });
        this.selectedFeatures.set([]);
        this.isSubmitting.set(false);
    }

    // Helper methods for form validation
    getFieldError(fieldName: string): string | null {
        const field = this.vehicleForm.get(fieldName);
        if (field && field.invalid && field.touched) {
            if (field.errors?.['required']) {
                return 'Este campo es obligatorio';
            }
            if (field.errors?.['pattern']) {
                return 'Formato inválido (ej: ABC-123)';
            }
            if (field.errors?.['minlength']) {
                return `Mínimo ${field.errors['minlength'].requiredLength} caracteres`;
            }
            if (field.errors?.['min']) {
                return `Valor mínimo: ${field.errors['min'].min}`;
            }
            if (field.errors?.['max']) {
                return `Valor máximo: ${field.errors['max'].max}`;
            }
        }
        return null;
    }

    isFieldInvalid(fieldName: string): boolean {
        const field = this.vehicleForm.get(fieldName);
        return !!(field && field.invalid && field.touched);
    }
}
